// файл, содержащий массив объектов с информацией о единицах измерения

export const data = [
    
    {
        "magnitude": "Длина",
        "unit(rus)": "метр",
        "unit(intern)": "metre (meter)",
        "designation(rus)": "м",
        "designation(intern)": "m",
    },
    {
        "magnitude": "Масса",
        "unit(rus)": "килограмм",
        "unit(intern)": "kilogram",
        "designation(rus)": "кг",
        "designation(intern)": "kg",
    },
    {
        "magnitude": "Время",
        "unit(rus)": "секунда",
        "unit(intern)": "second",
        "designation(rus)": "с",
        "designation(intern)": "s",
    },
    {
        "magnitude": "Сила тока",
        "unit(rus)": "ампер",
        "unit(intern)": "ampere",
        "designation(rus)": "A",
        "designation(intern)": "A",
    },
    {
        "magnitude": "Термодинамическая температура",
        "unit(rus)": "кельвин",
        "unit(intern)": "kelvin",
        "designation(rus)": "K",
        "designation(intern)": "K",
    },
    {
        "magnitude": "Количество вещества",
        "unit(rus)": "моль",
        "unit(intern)": "mole",
        "designation(rus)": "моль",
        "designation(intern)": "mol",
    },
    {
        "magnitude": "Плоский угол",
        "unit(rus)": "радиан",
        "unit(intern)": "radian",
        "designation(rus)": "рад",
        "designation(intern)": "rad",
    },
    {
        "magnitude": "Телесный угол",
        "unit(rus)": "стерадиан",
        "unit(intern)": "steradian",
        "designation(rus)": "Ср",
        "designation(intern)": "sr",
    },
    {
        "magnitude": "Температура по шкале Цельсия",
        "unit(rus)": "градус Цельсия",
        "unit(intern)": "degree Celsius",
        "designation(rus)": "C",
        "designation(intern)": "C",
    },
    {
        "magnitude": "Частота",
        "unit(rus)": "герц",
        "unit(intern)": "hertz",
        "designation(rus)": "Гц",
        "designation(intern)": "Hz",
    },
    {
        "magnitude": "Сила",
        "unit(rus)": "ньютон",
        "unit(intern)": "newton",
        "designation(rus)": "Н",
        "designation(intern)": "N",
    },
    {
        "magnitude": "Энергия",
        "unit(rus)": "джоуль",
        "unit(intern)": "joule",
        "designation(rus)": "Дж",
        "designation(intern)": "J",
    },
    {
        "magnitude": "Мощность",
        "unit(rus)": "ватт",
        "unit(intern)": "watt",
        "designation(rus)": "Вт",
        "designation(intern)": "W",
    },
    {
        "magnitude": "Давление",
        "unit(rus)": "паскаль",
        "unit(intern)": "pascal",
        "designation(rus)": "Па",
        "designation(intern)": "Pa",
    },
    {
        "magnitude": "Световой поток",
        "unit(rus)": "люмен",
        "unit(intern)": "lumen",
        "designation(rus)": "лм",
        "designation(intern)": "lm",
    },
    {
        "magnitude": "Освещённость",
        "unit(rus)": "люкс",
        "unit(intern)": "lux",
        "designation(rus)": "лк",
        "designation(intern)": "lx",
    },
    {
        "magnitude": "Электрический заряд",
        "unit(rus)": "кулон",
        "unit(intern)": "coulomb",
        "designation(rus)": "Кл",
        "designation(intern)": "C",
    },
    {
        "magnitude": "Разность потенциалов",
        "unit(rus)": "вольт",
        "unit(intern)": "volt",
        "designation(rus)": "В",
        "designation(intern)": "V",
    },
    {
        "magnitude": "Сопротивление",
        "unit(rus)": "ом",
        "unit(intern)": "ohm",
        "designation(rus)": "Ом",
        "designation(intern)": "Ω",
    },
    {
        "magnitude": "Электроёмкость",
        "unit(rus)": "фарад",
        "unit(intern)": "farad",
        "designation(rus)": "Ф",
        "designation(intern)": "F",
    },
    {
        "magnitude": "Магнитный поток",
        "unit(rus)": "вебер",
        "unit(intern)": "weber",
        "designation(rus)": "Вб",
        "designation(intern)": "Wb",
    },
    {
        "magnitude": "Магнитная индукция",
        "unit(rus)": "тесла",
        "unit(intern)": "tesla",
        "designation(rus)": "Тл",
        "designation(intern)": "T",
    },
    {
        "magnitude": "Индуктивность",
        "unit(rus)": "генри",
        "unit(intern)": "henry",
        "designation(rus)": "Гн",
        "designation(intern)": "H",
    },
    {
        "magnitude": "Электрическая проводимость",
        "unit(rus)": "сименс",
        "unit(intern)": "siemens",
        "designation(rus)": "См",
        "designation(intern)": "S",
    },
    {
        "magnitude": "Активность (радиоактивного источника)",
        "unit(rus)": "беккерель",
        "unit(intern)": "becquerel",
        "designation(rus)": "Бк",
        "designation(intern)": "Bq",
    },
    {
        "magnitude": "Поглощённая доза ионизирующего излучения",
        "unit(rus)": "грэй",
        "unit(intern)": "gray",
        "designation(rus)": "Гр",
        "designation(intern)": "Gy",
    },
    {
        "magnitude": "Эффективная доза ионизирующего излучения",
        "unit(rus)": "",
        "unit(intern)": "",
        "designation(rus)": "",
        "designation(intern)": "",
    },
    {
        "magnitude": "Эффективная доза ионизирующего излучения",
        "unit(rus)": "зиверт",
        "unit(intern)": "sievert",
        "designation(rus)": "Зв",
        "designation(intern)": "Sv",
    },
    {
        "magnitude": "Активность катализатора",
        "unit(rus)": "катал",
        "unit(intern)": "katal",
        "designation(rus)": "кат",
        "designation(intern)": "ka",
    }
    
    ];



